use std::env;
use std::error::Error;
use std::fs;
use std::io;
use std::path::PathBuf;

const BUILD_INSTANCE_ID_BYTES: usize = 32;
const MAX_TARGET_TRIPLE_BYTES: usize = 255;
const GENERATED_FILE_NAME: &str = "runtime_host_build_metadata_generated.rs";

// Complete in-workspace dependency graph of the final RuntimeHost executable.
// A composition-root or path-dependency change must embed a fresh identity in
// the final executable, never in a reusable library artifact.
const FINAL_ARTIFACT_INPUTS: &[&str] = &[
    "build.rs",
    "Cargo.toml",
    "src",
    "../paraegox-runtime/Cargo.toml",
    "../paraegox-runtime/src",
    "../paraegox-runtime-contracts/Cargo.toml",
    "../paraegox-runtime-contracts/src",
    "../paraegox-kernel/Cargo.toml",
    "../paraegox-kernel/src",
    "../../Cargo.toml",
    "../../Cargo.lock",
];

const FINAL_ARTIFACT_ENV_INPUTS: &[&str] = &[
    "RUSTFLAGS",
    "CARGO_ENCODED_RUSTFLAGS",
    "RUSTC_WRAPPER",
    "RUSTC_WORKSPACE_WRAPPER",
];

fn main() -> Result<(), Box<dyn Error>> {
    for input in FINAL_ARTIFACT_INPUTS {
        println!("cargo:rerun-if-changed={input}");
    }
    for input in FINAL_ARTIFACT_ENV_INPUTS {
        println!("cargo:rerun-if-env-changed={input}");
    }

    let target = required_env("TARGET")?;
    if !is_canonical_target_triple(&target) {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "Cargo TARGET is not a canonical Runtime target triple",
        )
        .into());
    }

    let mut build_instance_id = [0_u8; BUILD_INSTANCE_ID_BYTES];
    getrandom::fill(&mut build_instance_id)?;
    if build_instance_id.iter().all(|byte| *byte == 0) {
        return Err(io::Error::other(
            "OS CSPRNG returned an all-zero RuntimeHost build instance ID",
        )
        .into());
    }

    let out_dir = env::var_os("OUT_DIR").ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::NotFound,
            "Cargo did not provide OUT_DIR to the RuntimeHost build script",
        )
    })?;
    let generated = format!(
        "// @generated by crates/paraegox-runtime-host/build.rs; do not edit.\n\
         const RUNTIME_HOST_BUILD_INSTANCE_ID: [u8; 32] = {build_instance_id:?};\n\
         const RUNTIME_HOST_BUILD_TARGET_TRIPLE: &str = {target:?};\n"
    );
    fs::write(PathBuf::from(out_dir).join(GENERATED_FILE_NAME), generated)?;
    Ok(())
}

fn required_env(name: &str) -> Result<String, io::Error> {
    env::var(name).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("Cargo did not provide valid Unicode {name}: {error}"),
        )
    })
}

fn is_canonical_target_triple(value: &str) -> bool {
    let bytes = value.as_bytes();
    !bytes.is_empty()
        && bytes.len() <= MAX_TARGET_TRIPLE_BYTES
        && bytes.first().is_some_and(u8::is_ascii_alphanumeric)
        && bytes.last().is_some_and(u8::is_ascii_alphanumeric)
        && bytes.iter().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'-' | b'_' | b'.')
        })
}
